markdown_extensions:
    - toc:
        permalink: True

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - python

site_name: GeneticEngine Documentation

nav:
    - Home: 'index.md'
    - Tutorial: 'tutorial.md'
    - Single and Multi-Objective: 'problems.md'
    - Defining Grammars:
      - Grammars: 'grammars.md'
      - Builtin Grammars: 'builtin_grammars.md'
    - MetaHandlers:
      - Introduction: 'metahandlers/'
      - List of MetaHandlers: 'metahandlers/api.md'
      - Define your own MetaHandlers: 'metahandlers/define.md'
    - Genetic Programming:
      - Genetic Programming Class: 'algorithms/genetic_programming.md'
      - Representations: 'representations.md'
    - Genetic Operators:
      - Selections: 'genetic_operators/selections.md'
    #- Code Reference: reference/

plugins:
  - search
  - gen-files:
      scripts:
      - docs/gen_ref_pages.py
  #- literate-nav:
      #nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          show_submodules: true
          docstring_style: "google"
          show_root_heading: true
          show_root_toc_entry: true
          show_root_full_path: true
          show_signature_annotations: true
          show_if_no_docstring: true
          show_category_heading: true
