[project]
name = "GeneticEngine"
version = "0.0.30"
description = "Genetic Programming with Types and Grammars"
authors = [
    {name = "Guilherme Espada", email = "gjespada@fc.ul.pt"},
    {name = "Leon Ingelse", email = "leoningelse@gmail.com"},
    {name = "Paulo Santos", email = "pacsantos@fc.ul.pt"},
    {name = "Pedro Barbosa", email = "psbarbosa@ciencias.ulisboa.pt"},
    {name = "Alcides Fonseca", email = "me@alcidesfonseca.com"}
]
readme = "Readme.md"
requires-python = "~=3.9"

[project.urls]
homepage = "https://github.com/alcides/GeneticEngine/"
repository = "https://github.com/alcides/GeneticEngine/"
documentation = "https://github.com/alcides/GeneticEngine/"

[project.license]
text = "https://opensource.org/licenses/MIT"

[build-system]
build-backend = 'setuptools.build_meta'
requires = [
    'setuptools >= 43.0.0',
]

[tool.docformatter]
syntax = 'google'
black = true
recursive = true
docstring-length = [60, 100]
blank = false
pre-summary-newline = true
close-quotes-on-newline = true
wrap-one-line = true

[tool.black]
line-length = 120


[tool.pycln]
all = true

[tool.isort]
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
