[project]
name = "GeneticEngine"
version = "0.0.8"
description = "Genetic Programming with Types and Grammars"
authors = [
    "Alcides Fonseca <me@alcidesfonseca.com>"
]
readme = "README.md"
python = "^3.9"
homepage = "https://github.com/alcides/GeneticEngine/"
repository = "https://github.com/alcides/GeneticEngine/"
documentation = "https://github.com/alcides/GeneticEngine/"

[project.license]
text = "https://opensource.org/licenses/MIT"

[build-system]
build-backend = 'setuptools.build_meta'
requires = [
    'setuptools >= 43.0.0',
]