[project]
name = "GeneticEngine"
version = "0.0.7"
description = "Genetic Programming with Types and Grammars"
authors = [
    "Alcides Fonseca <me@alcidesfonseca.com>"
]
license = "MIT"
readme = "README.md"
python = "^3.9"
homepage = "https://github.com/alcides/GeneticEngine/"
repository = "https://github.com/alcides/GeneticEngine/"
documentation = "https://github.com/alcides/GeneticEngine/"

[build-system]
build-backend = 'setuptools.build_meta'
requires = [
    'setuptools >= 43.0.0',
]

[mypy]
python_version = "3.9"
mypy_path = .
ignore_missing_imports = True
namespace_packages = True